export const routeNames = {
  DEFAULT: "DEFAULT",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  HOME: "HOME",
  ALBUM: "ALBUM",
  ALBUM_DETAILS: "ALBUM DETAILS",
  ARTIST_DETAILS: "ARTIST DETAILS",
  ARTIST: "ARTIST",
  COLLECTION: "COLLECTION",
  EXPLORE: "EXPLORE",
  MY_COLLECTION: "MY_COLLECTION",
  DRAFT_COLLECTION_DETAIL: "DRAFT_COLLECTION_DETAIL",
  COLLECTION_DETAILS: "COLLECTION_DETAILS",
  USER_DETAIL: "USER_DETAIL",
  ME: "ME"
};
