export const routeNames = {
  DEFAULT: "DEFAULT",
  LOGIN: "LOGIN",
  SIGNUP: "SIGNUP",
  HOME: "HOME",
  ALBUM: "ALBUM",
  ALBUM_DETAILS: "ALBUM DETAILS",
  ARTIST: "ARTIST",
  COLLECTION: "COLLECTION"
};
